version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "19:30"
      timezone: Europe/Paris
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
      time: "19:30"
      timezone: Europe/Paris