apiVersion: camel.apache.org/v2alpha1
kind: Integration
metadata:
  name: "sample-dapr"
spec:
  flows:
    - route:
        from:
          uri: "dapr-pubsub:sensors/iot"
          steps:
            - to: "log:from-pubsub"
    
