---
apiVersion: camel.apache.org/v2alpha1
kind: Integration
metadata:
  name: "mqtt2kafka"
  namespace: "dapr-system"
spec:
  flows:
    - route:
        from:
          uri: "mqtt:camel-iot"
          parameters:
            broker: "tcp://test.mosquitto.org:1883"
          steps:
            - to: "log:from-pubsub"
            - choice:
                when:
                  - jq: '.source == "sensor-1"'
                    steps:
                      - to: "log:sensor-1"
                      - transform:
                          jq: '.data'
                      - transform:
                          wasm: "quay.io/lburgazzoli/camel-go-wasm:latest?etc/wasm/fn/to_upper.wasm"
                      - to:
                          uri: "kafka:near"
                          parameters:
                            brokers: "redpanda-0.redpanda.redpanda-system.svc.cluster.local:9093"
                      - to: "log:near"
                  - jq: '.source == "sensor-2"'
                    steps:
                      - to: "log:sensor-2"
                      - transform:
                          jq: '.data'
                      - transform:
                          wasm: "quay.io/lburgazzoli/camel-go-wasm:latest?etc/wasm/fn/to_lower.wasm"
                      - to:
                          uri: "kafka:far"
                          parameters:
                            brokers: "redpanda-0.redpanda.redpanda-system.svc.cluster.local:9093"
                otherwise:
                  steps:
                    - to: "log:unknown"
