---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: camel-control-plane-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - secrets
  - serviceaccounts
  - services
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - camel.apache.org
  resources:
  - integrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - camel.apache.org
  resources:
  - integrations/finalizers
  verbs:
  - update
- apiGroups:
  - camel.apache.org
  resources:
  - integrations/status
  verbs:
  - get
  - patch
  - update
