version: "3.8"
services:
  mosquitto:
    image: "eclipse-mosquitto:2"
    networks:
      - gamel
    ports:
      - target: 8883
        published: 8883
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./support/mqtt/mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
        read_only: true
  kafka:
    image: "docker.io/redpandadata/redpanda:v22.3.13"
    command:
      - redpanda
      - start
      - --mode
      - dev-container
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    networks:
      - gamel
    depends_on:
      - mosquitto
  integration:
    image: ""
    command:
      - redpanda
      - start
      - --mode
      - dev-container
    networks:
      - gamel
    depends_on:
      - mosquitto
      - kafka
    volumes:
      - type: bind
        source: ./binds/sub
        target: /binds
        read_only: false
networks:
  gamel:
    external: false
