/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2alpha1

import (
	v2alpha1 "github.com/lburgazzoli/camel-go/api/camel/v2alpha1"
)

// FlowApplyConfiguration represents an declarative configuration of the Flow type for use
// with apply.
type FlowApplyConfiguration struct {
	v2alpha1.RawMessage `json:",inline"`
}

// FlowApplyConfiguration constructs an declarative configuration of the Flow type for use with
// apply.
func Flow() *FlowApplyConfiguration {
	return &FlowApplyConfiguration{}
}
