/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// IntegrationStatusApplyConfiguration represents an declarative configuration of the IntegrationStatus type for use
// with apply.
type IntegrationStatusApplyConfiguration struct {
	Phase              *string        `json:"phase,omitempty"`
	Conditions         []v1.Condition `json:"conditions,omitempty"`
	ObservedGeneration *int64         `json:"observedGeneration,omitempty"`
}

// IntegrationStatusApplyConfiguration constructs an declarative configuration of the IntegrationStatus type for use with
// apply.
func IntegrationStatus() *IntegrationStatusApplyConfiguration {
	return &IntegrationStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *IntegrationStatusApplyConfiguration) WithPhase(value string) *IntegrationStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *IntegrationStatusApplyConfiguration) WithConditions(values ...v1.Condition) *IntegrationStatusApplyConfiguration {
	for i := range values {
		b.Conditions = append(b.Conditions, values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *IntegrationStatusApplyConfiguration) WithObservedGeneration(value int64) *IntegrationStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
