name: Build PR

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: setup-oras
        uses: oras-project/setup-oras@v1
      - name: setup-go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: "Set Up Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: "wasm32-unknown-unknown"
      - name: wasm
        run: |
          export UUID=$(uuidgen | tr "[:upper:]" "[:lower:]")
          export WASM_CONTAINER_IMAGE="ttl.sh/${UUID}-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}:1h"

          make wasm/build
          make wasm/publish
      - name: check
        run: |
          make check
      - name: test
        run: |
          make test
