name: Build PR

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: setup-go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: "Set Up Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: 'wasm32-unknown-unknown'
      - name: wasm
        run: |
          export UUID=$(uuidgen | tr "[:upper:]" "[:lower:]")
          export WASM_CONTAINER_IMAGE="ttl.sh/${UUID}-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}:1h"

          make wasm/build
          make wasm/publish
      - name: check
        run: |
          make check
      - name: test
        run: |
          make test
