name: Build Main

on:
  push:
    branches:
      - main

env:
  CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  WASM_CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: setup-go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: "Login to Container registry"
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}  
      - name: "Set Up Tinygo" 
        uses: acifani/setup-tinygo@b2ba42b249c7d3efdfe94166ec0f48b3191404f7 # v2.0.0
        with:
          tinygo-version: '0.31.2'
      - name: 'Build WASM'
        run: |
          make wasm/build/ci
      - name: 'Push WASM'
        run: |
          make wasm/publish
      - name: check
        run: |
          make check
      - name: test
        run: |
          make test
      - name: 'Push Image'
        run: |
          make image/publish
