name: Build PR

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: setup-go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
          cache-dependency-path: go.sum      
      - name: "Set Up Tinygo" 
        uses: acifani/setup-tinygo@b2ba42b249c7d3efdfe94166ec0f48b3191404f7 # v2.0.0
        with:
          tinygo-version: '0.31.2'
          
      - name: wasm
        run: |
          export UUID=$(uuidgen | tr "[:upper:]" "[:lower:]")
          export WASM_CONTAINER_IMAGE="ttl.sh/${UUID}-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}:1h"

          make wasm/build/ci
          make wasm/publish

      - name: check
        run: |
          make check
      - name: test
        run: |
          make test
