name: Build Main

on:
  push:
    branches:
      - main

env:
  CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  WASM_CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: setup-go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: "Login to Container registry"
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}  
      - name: "Set Up Tinygo" 
        uses: acifani/setup-tinygo@b2ba42b249c7d3efdfe94166ec0f48b3191404f7 # v2.0.0
        with:
          tinygo-version: '0.30.0'
      - name: 'Build WASM'
        run: |
          make wasm/build/ci
      - name: 'Push WASM'
        run: |
          make wasm/publish
      - name: check
        run: |
          make check
      - name: test
        run: |
          make test
      - name: 'Push Image'
        run: |
          make image/publish
