name: Build Main

on:
  push:
    branches:
      - main

env:
  CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  WASM_CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: setup-oras
        uses: oras-project/setup-oras@v1
      - name: setup-go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: "Login to Container registry"
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      - name: "Set Up Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: "wasm32-unknown-unknown"
      - name: "Build WASM"
        run: |
          make wasm/build
      - name: "Push WASM"
        run: |
          make wasm/publish
      - name: check
        run: |
          make check
      - name: test
        run: |
          make test
      - name: "Push Image"
        run: |
          make image/publish
