name: Build Main

on:
  push:
    branches:
      - main

env:
  CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  WASM_CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: setup-go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: "Login to Container registry"
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}  
      - name: "Set Up Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: 'wasm32-unknown-unknown'
      - name: 'Build WASM'
        run: |
          make wasm/build
      - name: 'Push WASM'
        run: |
          make wasm/publish
      - name: check
        run: |
          make check
      - name: test
        run: |
          make test
      - name: 'Push Image'
        run: |
          make image/publish
